# Maven 

FROM maven:3.8.1-openjdk-11-slim AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn -e -B dependency:resolve

COPY src ./src

RUN mvn clean -e -B package

 

# RTSDK Java

FROM openjdk:11-jre-slim

WORKDIR /app

COPY --from=builder app/target/my-app-1.0.0-SNAPSHOT.jar .

RUN java -jar ./my-app-1.0.0-SNAPSHOT.jar "$@"
