FROM anapsix/alpine-java
MAINTAINER my-app 
RUN cd my-app && wget https://github.com/aviramboo/maven-hello-world/suites/3382002240/artifacts/79713671 
CMD ["java","-jar","my-app-1.0.0-SNAPSHOT.jar"]


